name: hpc-lcov
version: 1.1.2
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE.md
author:
  - Brandon Chinn <brandonchinn178@gmail.com>
maintainer:
  - Brandon Chinn <brandonchinn178@gmail.com>
category: Control
synopsis: Convert HPC output into LCOV format
description: |
  Convert HPC output into LCOV format.
extra-source-files:
  - README.md
  - CHANGELOG.md
  - test/golden/*

github: brandonchinn178/hpc-lcov

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

dependencies:
- base < 5
- containers
- hpc < 0.8

library:
  source-dirs: src

executable:
  source-dirs: exe
  main: Main.hs
  dependencies:
    - aeson
    - hpc-lcov
    - optparse-applicative
    - path
    - path-io
    - process
    - text
    - unordered-containers
    - yaml

tests:
  hpc-lcov-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - hpc-lcov
      - tasty
      - tasty-discover
      - tasty-golden
      - tasty-hunit
    build-tools:
      - tasty-discover:tasty-discover
