resolver: nightly-2024-12-20

extra-deps:
  - path-0.9.5
  - path-io-1.8.2
allow-newer: true
allow-newer-deps:
  # https://github.com/commercialhaskell/path/issues/195
  - path

ghc-options:
  '$locals': -Werror
