name: minimal-example
version: 0.1.0

dependencies:
  - base

library:
  source-dirs: src
  other-modules: []  # don't generate Paths_minimal_example.hs

tests:
  minimal-example-test:
    source-dirs: test
    other-modules: []  # don't generate Paths_minimal_example.hs
    main: Main.hs
    dependencies:
      - minimal-example
