name: Release
on: workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - ci

    env:
      VERSION: ${{ needs.ci.outputs.version }}

    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/download-artifact@v3
        with:
          name: hpc-lcov-binary-ubuntu-latest
          path: ./bin/
      -
        uses: actions/download-artifact@v3
        with:
          name: hpc-lcov-binary-macos-latest
          path: ./bin/
      -
        uses: actions/download-artifact@v3
        with:
          name: hpc-lcov-sdist
          path: ./sdist/
      -
        id: cabal_file
        uses: haskell-actions/parse-cabal-file@v1
        with:
          cabal_file: hpc-lcov.cabal
      -
        name: Get CHANGELOG section
        run: |
          sed '/^# Unreleased/,/^$/d' CHANGELOG.md > /tmp/changelog-without-unreleased
          if [[ "$(head -n 1 /tmp/changelog-without-unreleased)" != "# v${VERSION}" ]]; then
            echo "CHANGELOG doesn't look updated" >&2
            exit 1
          fi
          sed '1 d; /^# v/,$ d' /tmp/changelog-without-unreleased > /tmp/changelog-body
      -
        name: Load Hackage token secret name
        id: hackage_token_secret
        run: |
          USERNAME="$(echo "${GITHUB_ACTOR}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
          echo "name=HACKAGE_TOKEN_${USERNAME}" >> "${GITHUB_OUTPUT}"
      -
        uses: haskell-actions/hackage-publish@v1
        with:
          hackageToken: ${{ secrets[steps.hackage_token_secret.outputs.name] }}
          packagesPath: ./sdist/
      -
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          body_path: /tmp/changelog-body
          draft: true
          target_commitish: ${{ github.sha }}
          files: |
            bin/hpc-lcov-${{ env.VERSION }}-linux-x86_64
            bin/hpc-lcov-${{ env.VERSION }}-osx-x86_64
          fail_on_unmatched_files: true
